services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    restart: no
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: study_sessions
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://myuser:mypassword@postgres:5432/study_sessions
      - ADMIN_USERNAME=Eva
      - ADMIN_PASSWORD_HASH=$$2b$12$4mB5mj7CSEbXNzmXqsbtwuLmkqgGv6jV0UPGtzZbeYuSJEOe47IpW
      - SECRET_KEY=your_random_secure_key
      - FORCE_HTTPS=true
      - USE_SECURE_COOKIES=true
    ports:
      - "5000:8000"
    volumes:
      - ./backend:/app
      - ./data/signatures:/app/data/signatures

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - PORT=5173

volumes:
  postgres-data:
