services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: study_sessions
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://myuser:mypassword@postgres:5432/study_sessions
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=$2b$12$KIfQbktCuX0B/69VdBTmhug1ju79Dbh.5EKTKG.OXzJVbrgsQzBim
      - SECRET_KEY=your_random_secure_key
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./data/signatures:/app/data/signatures

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres-data: