"""Recreated study_session without user_id

Revision ID: 33067db5e456
Revises: 
Create Date: 2025-03-18 20:11:40.548921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33067db5e456'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('session_topic', sa.String(length=200), nullable=False),
    sa.Column('signature_path', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_session')
    # ### end Alembic commands ###
